---
app_user: appwebs1
app_dir: /appwebs_01
app_group: websapps
super_user: root

filesystem_type: ext4
physical_disk: /dev/sdc1
physical_disk_raw: /dev/sdc

websphere_admin: ibmadmin
websphere_admin_pwd: "venerari123"

app_profile_server: server1
profile_name: AppSrv01
was_nodename: Node01

